name: megadey_mobile
description: Megadey mobile app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.1.1
  badges: ^3.1.1
  observable_ish: ^4.0.3
  flutter_svg: ^1.0.3
  image_cropper: ^3.0.1
  upgrader: ^4.1.1
  intl_phone_number_input: ^0.7.0+2
  lottie: ^2.3.0
  intl: ^0.17.0
  widget_and_text_animator: ^1.0.9
  percent_indicator: ^4.2.2
  emoji_picker_flutter: ^1.1.1
  dio: ^4.0.4
  loading_overlay: ^0.3.0
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  easy_stepper: ^0.6.0
  fl_chart: ^0.60.0
  get_it: ^7.2.0
  permission_handler: ^10.2.0
  stacked: ^3.2.2
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.2
  basic_utils: ^4.2.1
  hive: ^2.2.3
  rflutter_alert: ^2.0.4
  image_picker: ^0.8.4+13
  hive_flutter: ^1.1.0
  pinput: ^2.2.31
  shimmer_animation: ^2.1.0+1
  loading_indicator: ^3.1.0
  flutter_local_notifications: ^9.6.1
  firebase_messaging: ^14.4.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0
  #  flutter_facebook_auth: ^4.4.0+1
  flutter_vibrate: ^1.3.0
  http_parser: ^4.0.1
  flick_video_player: ^0.5.0
  custom_timer: ^0.1.2
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  slide_countdown: ^0.3.2
  webview_flutter: ^4.2.0
  top_snackbar_flutter: ^3.1.0
  the_apple_sign_in: ^1.1.1
  flutter_facebook_auth: ^4.4.0+1
  timeago: ^3.3.0
  flutter_carousel_widget: ^1.2.0
  fluttertoast: ^8.2.1
  firebase_database: ^10.1.0
  firebase_storage: ^11.1.0
  firebase_analytics: ^10.2.1
  share_plus: ^6.3.1
  easy_image_viewer: ^1.2.1
  timer_count_down: ^2.2.1



dependency_overrides:
  image_picker_android: 0.8.4+13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
#  adaptive_icon_foreground: "assets/images/logo.png"
#  adaptive_icon_background: "#FFFFFF"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/icons/navigation/
    - assets/icons/categories/
    - assets/animations/
    - .env


  fonts:
    - family: dm_sans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700